.. _ood_job_composer:

Job Composer
------------

About
~~~~~

The Job Composer contains all the tools that allow you to launch your jobs. This
goes from basic job script building, adding necessary files, to building and
using templates for easier job creation. Under the job composer tab you can find
two other menus, namely ‘Jobs’ and ‘Templates’. As templates are the backbone of
job creation in Open OnDemand, we will start by explaining these. The ‘Jobs’
menu is pretty much self-explanatory once understanding this.

Templates
~~~~~~~~~

.. tab-set::

   .. tab-item:: KU Leuven/UHasselt

      .. include:: job-composer-templates-leuven.rst


   .. tab-item:: VUB

      (not available at this time)

Creating jobs
~~~~~~~~~~~~~

.. tab-set::

   .. tab-item:: KU Leuven/UHasselt

      .. container::

         .. include:: job-composer-jobs-leuven.rst


   .. tab-item:: VUB

      (not available at this time)

