# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

from datetime import datetime

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "VSC documentation"
copyright = f"{datetime.now().year}, VSC (Vlaams Supercomputing Center)"
author = "VSC (Vlaams Supercomputing Center)"

# The short X.Y version
version = "2.1"
# The full version, including alpha/beta/rc tags
release = "2.1"

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'sphinx_design',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinxcontrib.redirects',
    'sphinx_sitemap',
    'notfound.extension',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The file extensions of source files. Sphinx considers the files with this
# suffix as sources. The value can be a dictionary mapping file extensions to
# file types.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = None

# To render double dashes in text as double dashes (and not as an "en dash"):
smartquotes_action = 'qe'  # instead of default 'qDe'

# Automatic numbering of figures
numfig = True

# -- Options for HTML output -------------------------------------------------

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = project

# Base URL of the documentation.
# (needed to generate the sitemap)
html_baseurl = 'https://docs.vscentrum.be/'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'pydata_sphinx_theme'

# Icon links on right side of the navbar
# https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/header-links.html#icon-links
html_navbar_icon_links = [
    {
        "name": "VSC on LinkedIn",
        "url": "https://www.linkedin.com/company/vschpc",
        "icon": "fa-brands fa-linkedin",
    },
    {
        "name": "VSC on GitHub",
        "url": "https://github.com/vscentrum",
        "icon": "fa-brands fa-square-github",
    },
    {
        "name": "VSC on X",
        "url": "https://x.com/VSC_HPC",
        "icon": "fa-brands fa-square-x-twitter",
    },
    {
        "name": "VSC on BlueSky",
        "url": "https://bsky.app/profile/vschpc.bsky.social",
        "icon": "_static/fa-square-bluesky.svg",
        "type": "local",
    },
    {
        "name": "VSC Website",
        "url": "https://www.vscentrum.be/",
        "icon": "_static/fa-square-vsc.svg",
        "type": "local",
    },
]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "navbar_persistent": ["search-button"],
    "navbar_align": "left",
    "header_links_before_dropdown": 8,
    "icon_links": html_navbar_icon_links,
    "search_bar_text": "Search in VSC Docs...",
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    "use_edit_page_button": True,
    "show_prev_next": False,
    "footer_start": ["copyright"],
    "footer_end": [],
    "pygments_light_style": "gruvbox-light",  # contrasty readable comments
    "pygments_dark_style": "monokai",  # contrasty readable comments
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['css/vsc.css']

# Extra files to be copied into the website build directory
html_extra_path = ['robots.txt']

# Logo in top bar
html_logo = "_static/vsc-docs-logo-2.png"

# Site favicon
html_favicon = "_static/favicon.ico"

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = {
    "index": [],
    "**": ["search-field", "sidebar-nav-bs"],
}

# Edit this page button
html_context = {
    "github_user": "hpcleuven",
    "github_repo": "VscDocumentation",
    "github_version": "master",
    "doc_path": "source",
}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'VSCdocumentationdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'VSCdocumentation.tex', 'VSC documentation Documentation',
     'VSC (Vlaams Supercomputing Center)', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'vscdocumentation', 'VSC documentation Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'VSCdocumentation', 'VSC documentation Documentation',
     author, 'VSCdocumentation', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- NotFound Extension ------------------------------------------------------
notfound_template = '404.html'
notfound_urls_prefix = ''

# -- Sitemap Extension -------------------------------------------------------
sitemap_url_scheme = "{link}"
sitemap_filename = "vsc-docs-sitemap.xml"

# -- Page redirects ----------------------------------------------------------
redirects_file = "redirects.list"

# -- MyST --------------------------------------------------------------------

myst_heading_anchors = 2
myst_enable_extensions = ["colon_fence"]

# -- RST Prolog --------------------------------------------------------------
# Non-brakable space
rst_prolog = """
.. |nbsp| unicode:: U+00A0
   :trim:
"""
# Badges
rst_prolog += """
.. |Optional| replace:: :bdg-primary:`Optional`
.. |Example| replace:: :bdg-info:`Example`
.. |Recommended| replace:: :bdg-success:`Recommended`
.. |Alert| replace:: :bdg-danger:`Alert`
.. |Warning| replace:: :bdg-warning:`Warning`
.. |Info| replace:: :bdg-info:`Info`
"""
# VSC Institute Badges
rst_prolog += """
.. |KUL| replace:: :bdg-info:`KU Leuven`
.. |KULUH| replace:: :bdg-info:`KU Leuven/UHasselt`
.. |UA| replace:: :bdg-danger:`UAntwerp`
.. |UG| replace:: :bdg-secondary:`UGent`
.. |UH| replace:: :bdg-info:`UHasselt`
.. |VUB| replace:: :bdg-primary:`VUB`
"""
### Links used multiple times across the documentation ###
# Links to VSC and VSC sites
rst_prolog += """
.. _eligible users: https://www.vscentrum.be/getaccess
.. _get in touch: https://www.vscentrum.be/getintouch
.. _Tier-1 project application: https://www.vscentrum.be/compute
.. _VSC account page: https://account.vscentrum.be/
.. _VSC Account - Edit Account: https://account.vscentrum.be/django/account/edit
.. _VSC Account - Edit VO: https://account.vscentrum.be/django/vo/edit
.. _VSC Account - New/Join VO: https://account.vscentrum.be/django/vo/join
.. _VSC Firewall: https://firewall.vscentrum.be
.. _VSC Training: https://www.vscentrum.be/vsctraining
.. _KU Leuven Open OnDemand page: https://ondemand.hpc.kuleuven.be/
.. _Service Catalog: https://icts.kuleuven.be/sc/HPC
.. _training waiting list: https://admin.kuleuven.be/icts/onderzoek/hpc/HPCintro-waitinglist
"""
# Links to hardware specifications
rst_prolog += """
.. _AMD EPYC 7282: https://www.amd.com/en/support/downloads/drivers.html/processors/epyc/epyc-7002-series/amd-epyc-7282.html#amd_support_product_spec
.. _AMD EPYC 7452: https://www.amd.com/en/support/downloads/drivers.html/processors/epyc/epyc-7002-series/amd-epyc-7452.html#amd_support_product_spec
.. _AMD EPYC 7543: https://www.amd.com/en/products/processors/server/epyc/7003-series/amd-epyc-7543.html
.. _AMD EPYC 9384X: https://www.amd.com/en/products/processors/server/epyc/4th-generation-9004-and-8004-series/amd-epyc-9384x.html
.. _AMD EPYC 9535: https://www.amd.com/en/products/processors/server/epyc/9005-series/amd-epyc-9535.html
.. _AMD EPYC 9335: https://www.amd.com/en/products/processors/server/epyc/9005-series/amd-epyc-9335.html
.. _AMD Instinct MI100: https://www.amd.com/en/products/accelerators/instinct/mi100.html
.. _Intel Xeon E5-2650v4: https://www.intel.com/content/www/us/en/products/sku/91767/intel-xeon-processor-e52650-v4-30m-cache-2-20-ghz/specifications.html
.. _Intel Xeon E5-2680v2: https://www.intel.com/content/www/us/en/products/sku/75277/intel-xeon-processor-e52680-v2-25m-cache-2-80-ghz/specifications.html
.. _Intel Xeon E5-2680v4: https://www.intel.com/content/www/us/en/products/sku/91754/intel-xeon-processor-e52680-v4-35m-cache-2-40-ghz/specifications.html
.. _Intel Xeon E5-2683v4: https://www.intel.com/content/www/us/en/products/sku/91766/intel-xeon-processor-e52683-v4-40m-cache-2-10-ghz/specifications.html
.. _Intel Xeon E7-8891v4: https://www.intel.com/content/www/us/en/products/sku/93795/intel-xeon-processor-e78891-v4-60m-cache-2-80-ghz/specifications.html
.. _Intel Xeon Gold 6132: https://www.intel.com/content/www/us/en/products/sku/123541/intel-xeon-gold-6132-processor-19-25m-cache-2-60-ghz/specifications.html
.. _Intel Xeon Gold 6148: https://www.intel.com/content/www/us/en/products/sku/120489/intel-xeon-gold-6148-processor-27-5m-cache-2-40-ghz/specifications.html
.. _NVIDIA A100: https://www.nvidia.com/en-us/data-center/a100/
.. _NVIDIA L40S: https://www.nvidia.com/en-us/data-center/l40s/
.. _NVIDIA Tesla P100: https://www.nvidia.com/en-in/data-center/tesla-p100/
.. _NVIDIA GeForce 1080Ti: https://www.nvidia.com/en-us/geforce/10-series/#1080-ti-spec
"""
# Links to Globus
rst_prolog += """
.. _Globus: https://www.globus.org
.. _Globus Documentation: https://docs.globus.org
.. _Globus Web Interface: https://app.globus.org/
.. _Globus Management Console: https://www.globus.org/app/login
.. _Globus Connect Server Installation Guide: https://docs.globus.org/globus-connect-server-installation-guide
.. _Globus How-To pages: https://docs.globus.org/how-to
.. _Globus Connect Personal: https://www.globus.org/globus-connect-personal
.. _Globus Groups How-To page: https://docs.globus.org/how-to/managing-groups
.. _Globus CLI documentation: https://docs.globus.org/cli/examples
.. _Globus-Timer-CLI on PyPi: https://pypi.org/project/globus-timer-cli
.. _Globus Python SDK documentation: https://globus-sdk-python.readthedocs.io/en/stable/index.html
.. _developers.globus.org: https://developers.globus.org/
.. _docs.globus.org: https://docs.globus.org
.. _www.globus.org: https://www.globus.org
"""
# Other links
rst_prolog += """
.. _Adaptive Computing documentation: https://support.adaptivecomputing.com/hpc-cloud-support-portal/
.. _Apptainer: https://apptainer.org
.. _Apptainer Documentation: https://apptainer.org/docs/user/main/
.. _Apptainer Quick Start: https://apptainer.org/docs/user/main/quick_start.html
.. _Apptainer Definition Files: https://apptainer.org/docs/user/main/definition_files.html
.. _Sylabs Remote Builder: https://cloud.sylabs.io/builder
.. _ARM-DDT video: https://developer.arm.com/tools-and-software/server-and-hpc/debug-and-profile/arm-forge/resources/videos
.. _ARM-MAP: https://www.arm.com/products/development-tools/hpc-tools/cross-platform/forge/map
.. _atools documentation: https://atools.readthedocs.io/en/latest/
.. _CP2K: https://www.cp2k.org/
.. _CPMD: http://www.cpmd.org/
.. _CUDA: https://developer.nvidia.com/cuda-zone
.. _cuDNN: https://developer.nvidia.com/cudnn
.. _Cyberduck: https://cyberduck.io
.. _Cygwin: https://www.cygwin.com/
.. _Docker: https://www.docker.com/
.. _download FileZilla: https://filezilla-project.org/download.php?show_all=1
.. _Eclipse download page: http://www.eclipse.org/downloads
.. _Eclipse packages download page: https://www.eclipse.org/downloads/packages/
.. _Eclipse: https://www.eclipse.org/
.. _EuroHPC: https://eurohpc-ju.europa.eu
.. _EuroHPC Access Calls: https://eurohpc-ju.europa.eu/access-our-supercomputers/eurohpc-access-calls_en
.. _FFTW documentation: http://www.fftw.org/#documentation
.. _FFTW: http://www.fftw.org/
.. _FileZilla project page: https://filezilla-project.org/
.. _GCC documentation: http://gcc.gnu.org/onlinedocs/
.. _GNU: https://www.gnu.org/
.. _GNU binutils documentation: https://sourceware.org/binutils/docs/
.. _GROMACS: http://www.gromacs.org/
.. _HPE MPT documentation: https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-a00037728en_us&docLocale=en_US
.. _Intel Fortran Compiler Documentation: https://www.intel.com/content/www/us/en/developer/tools/oneapi/fortran-compiler-documentation.html
.. _Intel MPI: https://www.intel.com/content/www/us/en/developer/tools/oneapi/mpi-library.html
.. _Intel MPI Documentation: https://www.intel.com/content/www/us/en/developer/tools/oneapi/mpi-library-documentation.html
.. _Intel MPI - Beginning Hybrid MPI/OpenMP Development: https://www.intel.com/content/www/us/en/developer/articles/technical/beginning-hybrid-mpiopenmp-development.html
.. _Intel oneAPI DPC Compiler Documentation: https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler-documentation.html
.. _Intel oneAPI MKL Documentation: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-documentation.html
.. _Intel oneAPI MKL Link Line Advisor: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html
.. _Intel oneAPI Python Distribution: https://www.intel.com/content/www/us/en/developer/tools/oneapi/distribution-for-python.html
.. _Intel oneAPI VTune Profiler: https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html
.. _Intel Software Documentation Library: https://www.intel.com/content/www/us/en/resources-documentation/developer.html
.. _Interoperability with OpenMP API: https://www.intel.com/content/www/us/en/docs/mpi-library/developer-reference-linux/2021-14/interoperability-with-openmp-api.html
.. _DigitalOcean Introduction to Linux Basics: https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-basics
.. _irods.org: https://irods.org/
.. _JellyfiSSH: https://apps.apple.com/gb/app/jellyfissh/id416399476?mt=12
.. _Jupyter: https://jupyter.org/
.. _JupyterLab documentation: https://docs.jupyter.org/en/latest/
.. _Keras: https://keras.io/
.. _LAPACK user guide: http://www.netlib.org/lapack/lug/
.. _LAPACK95 user guide: http://www.netlib.org/lapack95/lug95/
.. _Linux kernel: https://www.kernel.org/
.. _Linux Newbie Administrator Guide: http://lnag.sourceforge.net/
.. _Linux Tutorials YouTube Channel: https://www.youtube.com/channel/UCut99_Fv1YEcpYRXNnUM7LQ
.. _LLNL Tutorials: https://hpc.llnl.gov/documentation/tutorials
.. _LLNL OpenMP Tutorial: https://hpc-tutorials.llnl.gov/openmp/
.. _LLNL Parallel Computing Tutorial: https://hpc.llnl.gov/documentation/tutorials/introduction-parallel-computing-tutorial
.. _LLNL Advanced MPI: https://hpc.llnl.gov/sites/default/files/DavidCronkSlides.pdf
.. _Lmod documentation: http://lmod.readthedocs.io/en/latest/
.. _Lmod: http://lmod.readthedocs.io/en/latest/
.. _MathWorks: https://nl.mathworks.com/
.. _MATLAB compiler documentation: https://nl.mathworks.com/help/compiler/index.html
.. _MobaXterm: https://mobaxterm.mobatek.net
.. _MPI Forum: https://www.mpi-forum.org/
.. _MPI Documents: https://www.mpi-forum.org/docs/
.. _MPICH: https://www.mpich.org/
.. _MVAPICH: http://mvapich.cse.ohio-state.edu/
.. _NAMD: http://www.ks.uiuc.edu/Research/namd/
.. _Netlib BLAS repository: http://www.netlib.org/blas/
.. _Netlib LAPACK repository: http://www.netlib.org/lapack/
.. _Netlib ScaLAPACK repository: http://www.netlib.org/scalapack/
.. _noVNC: https://novnc.com/
.. _NoMachine: https://www.nomachine.com/
.. _NX Client download: https://download.nomachine.com/enterprise/?product=enterprise-client
.. _ollama: https://ollama.com
.. _oneAPI Threading Building Blocks: https://uxlfoundation.github.io/oneTBB/
.. _Open MPI Documentation: https://www.open-mpi.org/doc
.. _Open MPI Explorations in Process Affinity: https://www.slideshare.net/jsquyres/open-mpi-explorations-in-process-affinity-eurompi13-presentation
.. _Open MPI: https://www.open-mpi.org/
.. _OpenBLAS Wiki: https://github.com/xianyi/OpenBLAS/wiki
.. _OpenBLAS: https://www.openblas.net/
.. _OpenMP compilers and tools: https://www.openmp.org/resources/openmp-compilers-tools/
.. _OpenMP: https://www.openmp.org
.. _Open OnDemand: https://openondemand.org/
.. _OpenSHMEM: http://www.openshmem.org/site/
.. _OpenSSH: https://www.openssh.com/
.. _Open WebUI: https://openwebui.com
.. _Paraview tutorial: https://vtk.org/Wiki/images/8/88/ParaViewTutorial38.pdf
.. _Paraview website: https://www.paraview.org/
.. _POSIX threads: https://en.wikipedia.org/wiki/POSIX_Threads
.. _PowerShell: https://learn.microsoft.com/en-us/powershell/
.. _PRACE: https://prace-ri.eu/
.. _PRACE Training Portal: https://training.prace-ri.eu/
.. _PRACE Tutorials: https://training.prace-ri.eu/index.php/prace-tutorials/
.. _PuTTY download site: https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
.. _PuTTY: https://www.chiark.greenend.org.uk/~sgtatham/putty/
.. _Red Hat Enterprise Linux: https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux
.. _qsub documentation: http://docs.adaptivecomputing.com/torque/6-1-2/adminGuide/torque.htm#topics/torque/commands/qsub.htm
.. _RStudio documentation: https://docs.posit.co/ide/user/
.. _ScaLAPACK user guide: http://netlib.org/scalapack/slug/
.. _Scalasca docs: http://www.scalasca.org/software/scalasca-2.x/documentation.html
.. _scp manual page: http://man.openbsd.org/scp
.. _Secure Shell: https://en.wikipedia.org/wiki/Secure_Shell
.. _sftp manual page: http://man.openbsd.org/sftp
.. _sbatch manual page: https://slurm.schedmd.com/sbatch.html
.. _ssh manual page: http://man.openbsd.org/ssh
.. _ssh-keygen manual page: http://man.openbsd.org/ssh-keygen
.. _ssh_config manual page: http://man.openbsd.org/ssh_config
.. _TensorBoard documentation: https://www.tensorflow.org/tensorboard/get_started
.. _TensorFlow: https://www.tensorflow.org/
.. _TigerVNC: https://tigervnc.org/
.. _Torque 6.0.1 documentation: http://docs.adaptivecomputing.com/torque/6-1-2/adminGuide/torque.htm
.. _TurboVNC download page: https://github.com/TurboVNC/turbovnc/releases
.. _TurboVNC: https://www.turbovnc.org/
.. _VirtualGL: https://en.wikipedia.org/wiki/VirtualGL
.. _VNC: https://en.wikipedia.org/wiki/VNC
.. _VSCode documentation: https://code.visualstudio.com/docs
.. _WinSCP: https://winscp.net
.. _WinSCP docs: https://winscp.net/eng/docs/start
.. _worker documentation: http://worker.readthedocs.io/en/latest/
.. _worker framework documentation: https://worker.readthedocs.io/en/latest/
.. _Windows Subsystem for Linux: https://learn.microsoft.com/en-us/windows/wsl/
.. _Xming website: http://www.straightrunning.com/XmingNotes/
.. _X Server: https://en.wikipedia.org/wiki/X.Org_Server
.. _X Window System: https://en.wikipedia.org/wiki/X_Window_System
"""
